### ISSUE TITLE
How can I add my own svgs?

### ISSUE THREAD

**Issue by G1sbi** [damnitharshit/nightly#3]

**Comment by shruuub** [comment]
Well, you fork it, add the svgs in the assets folder, and, if needed change the index.html file to your needs too.

**Comment by G1sbi** [comment]
@shruuub I'm kinda new to this, so thanks for the explanation :)

**Comment by damnitharshit** [comment]
@G1sbi You **can** do that, but you don't **need** to, like you can just follow the installation instructions, download the icons locally and then add the file path through the site settings and the site remembers everything you change. (as long as you don't clear the browser cache)

**Comment by shruuub** [comment]
Yup, just found the gh version to be more convinient since I empty my cache etc. after Browser close, and, cross-plattforn availability with github pages.
