### ISSUE TITLE
customisation

### ISSUE THREAD

**Issue by nobody48sheldor** [damnitharshit/nightly#5]
Hi I really liked nightly, but we cannot really change stuff, so I made a flask version in which we can locally host the page and thus make our own modification, maybe check my fork out, and maybe implement a similar way of loading the page, so that we can have different flavors of nightly

overall a great web greeter, nice job dude

**Comment by damnitharshit** [comment]
Thanks for the suggestion and love your work! I am sorta new to web dev so it'll take me some time, but I'll surely try to implement it. Although one thing I'd like to state is that my major goal with v2.0 was to make it more user friendly and less tech oriented, which of course came with some customisation compromises. I thought that the people who'd need more tinkering would generally be the people who love fiddling with the code anyways, so I left everything else to be a diy thing. Your version, adding more configurability, also adds a layer of complexity, so It'll also take me some time to make it more user-friendly. 
That said, I'd again like to thank you for your thoughts and feedback!
