### ISSUE TITLE
What License?

### ISSUE THREAD

**Issue by Teddy-Kun** [damnitharshit/nightly#8]
I would like to fork the project for my personal needs and of course publish my changes.
However your project does not have a license associated with it so technically I am legally not allowed to do so.
I would appreciated if you could just add a license to it, thanks!

**Comment by damnitharshit** [comment]
Thank you for your interest in my project! 

I've just added an MIT License to the repository, so you're now free to fork the project, make your changes, and publish them as you'd like.

**Comment by Teddy-Kun** [comment]
Alright, thank you!
